server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <GITHUB APP ID>
            client-secret: <GITHUB APP SECRET>
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
logging:
  level:
    org:
      springframework:
        INFO